name: ACT TEST
env:
  SOURCE_REPO: LouDnl/USBSID-Pico-driver
  AUTOMATIC_MONITOR: true
  FILES: "README.md LICENSE USBSID* vice-makefile/Makefile.am" # seperate multiple entries with ,
  THE_SERVER: ${{ github.server_url }}
  PATH_SOURCE_CHECKOUT: temp_folder
on:
  workflow_dispatch:
concurrency:
  group: USBSID-Pico TEST Build
  cancel-in-progress: true

jobs:
  build_deb:
    name: Build MacOs Package
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
          ui: [ { name: 'GTK3',
                  conf: '--enable-gtk3ui --with-pulse',
                  deps: 'libevdev-dev libglew-dev libgtk-3-dev libpulse-dev' },
                # { name: 'SDL2',
                #   conf: '--enable-sdl2ui --with-sdlsound --without-pulse',
                #   deps: 'libsdl2-dev libsdl2-image-dev' },
                # { name: 'SDL1',
                #   conf: '--enable-sdl1ui --with-sdlsound --without-pulse',
                #   deps: 'libsdl1.2-dev libsdl-image1.2-dev' },
                # { name: 'Headless',
                #   conf: '--enable-headlessui --with-pulse',
                #   deps: 'libpulse-dev' }
                  ]
    steps:

      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Checkout USBSID-Pico driver
        uses: actions/checkout@v4
        with:
          repository: ${{ env.SOURCE_REPO }}
          path: ${{ env.PATH_SOURCE_CHECKOUT }}

      - name: Copy files
        run: |
          mkdir -p vice/src/lib/libusbsiddrv
          cd $PATH_SOURCE_CHECKOUT
          cp $FILES ../vice/src/lib/libusbsiddrv/
          cd ..
          pwd

      - name: deps [macOS]
        if: runner.os == 'macOS'
        run: |
          export HOMEBREW_NO_INSTALL_CLEANUP=1
          brew update
          brew upgrade || true
          brew uninstall --ignore-dependencies --force pkg-config@0.29.2
          brew install \
            autoconf \
            automake \
            build-essential \
            libtool \
            pkgconf \
            coreutils \
            gnu-sed \
            libgcrypt \
            xa \
            libusb \
            libusb-compat \
            byacc \
            devscripts \
            dos2unix \
            fakeroot \
            flex \
            libasound-dev \
            libcap-dev \
            libcurl4-openssl-dev \
            libflac-dev \
            libgif-dev \
            libieee1284-3-dev \
            libmp3lame-dev \
            libmpg123-dev \
            libpcap-dev \
            libpng-dev \
            libvorbis-dev \
            portaudio19-dev \
            texinfo \
            texlive-fonts-recommended \
            texlive-latex-extra \
            xa65 \
            libevdev-dev \
            libglew-dev \
            libgtk-3-dev \
            libpulse-dev
      - name: Build
        run: |
          mkdir -p build/usr
          cd vice
          ./src/buildtools/genvicedate_h.sh
          ./autogen.sh
          # ALSA is required for SDL2 as well for midi support
          ./configure --enable-option-checking=fatal \
                      --prefix=/usr \
                      --enable-gtk3ui \
                      --with-pulse \
                      --disable-arch \
                      --disable-html-docs \
                      --enable-usbsid \
                      --enable-catweasel \
                      --enable-cpuhistory \
                      --enable-ethernet \
                      --enable-midi \
                      --enable-parsid \
                      --enable-pdf-docs \
                      --with-alsa \
                      --with-fastsid \
                      --with-flac \
                      --with-gif \
                      --with-lame \
                      --with-libcurl \
                      --with-libieee1284 \
                      --with-mpg123 \
                      --with-png \
                      --with-portaudio \
                      --with-resid \
                      --with-vorbis
          make -j2 -s --no-print-directory
          make DESTDIR=$HOME/build install
