name: BUILD TEST
env:
  SOURCE_REPO: LouDnl/USBSID-Pico-driver
  AUTOMATIC_MONITOR: true
  FILES: "README.md LICENSE USBSID* vice-makefile/Makefile.am" # seperate multiple entries with ,
  THE_SERVER: ${{ github.server_url }}
  PATH_SOURCE_CHECKOUT: temp_folder
  DEPS_PREFIX: /opt/homebrew
  PATH_ARTIFACTS: dist
on:
  workflow_dispatch:
concurrency:
  group: USBSID-Pico TEST Build
  cancel-in-progress: true

jobs:
  build_deb:
    name: Build MacOs Package
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
          ui: [ { name: 'GTK3',
                  conf: '--enable-gtk3ui',
                  deps: 'gtk+3' },
                { name: 'SDL2',
                  conf: '--enable-sdl2ui --with-sdlsound --without-pulse',
                  deps: 'sdl2 sdl2_image' },
                # { name: 'SDL1',
                #   conf: '--enable-sdl1ui --with-sdlsound --without-pulse',
                #   deps: 'sdl sdl12-compat sdl2_image' },
                { name: 'Headless',
                  conf: '--enable-headlessui --with-pulse',
                  deps: '' }
              ]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Checkout USBSID-Pico driver
        uses: actions/checkout@v4
        with:
          repository: ${{ env.SOURCE_REPO }}
          path: ${{ env.PATH_SOURCE_CHECKOUT }}

      - name: Copy files
        run: |
          mkdir -p vice/src/lib/libusbsiddrv
          cd $PATH_SOURCE_CHECKOUT
          cp $FILES ../vice/src/lib/libusbsiddrv/
          cd ..
          pwd

      - name: deps [macOS]
        if: runner.os == 'macOS'
        run: |
          export HOMEBREW_NO_INSTALL_CLEANUP=1
          brew update
          brew upgrade || true
          brew uninstall --ignore-dependencies --force pkg-config@0.29.2
          brew install \
            dos2unix \
            autoconf \
            automake \
            libtool \
            pkgconf \
            coreutils \
            gnu-sed \
            libgcrypt \
            xa \
            librsvg \
            adwaita-icon-theme \
            glew \
            libusb \
            libusb-compat \
            ${{ matrix.ui.deps }}
      - name: Build
        run: |
          mkdir -p build/usr
          cd vice
          ./src/buildtools/genvicedate_h.sh
          ./autogen.sh
          # ALSA is required for SDL2 as well for midi support
          ./configure --enable-option-checking=fatal \
                      --prefix=/usr \
                      --disable-arch \
                      --enable-usbsid \
                      --enable-cpuhistory \
                      --enable-parsid \
                      --with-pulse \
                      --with-alsa \
                      --with-fastsid \
                      --with-resid \
                      ${{ matrix.ui.conf }}
          make -j $(sysctl -n hw.ncpu) -s
          make DESTDIR=$HOME/build install
          cd ..
          mkdir $PATH_ARTIFACTS
          cd $PATH_ARTIFACTS
          tar cvzf vice-${{ matrix.ui.name }}.tgz -C $HOME/build .
          pwd
          ls -l
